recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
  - name: vietnamese_tokenizer.VietnameseTokenizer
    tokenizer: underthesea
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: fasttext_featurizer.FastTextFeaturizer
    cache_path: fasttext/cc.vi.300.bin
    file: cc.vi.300.bin
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True

# recipe: default.v1
# assistant_id: 20230326-061134-bounded-sweep
# language: "vi"

# pipeline:
#   - name: "SpacyNLP"
#     model: "vi"
#   - name: "SpacyTokenizer"
#   - name: "SpacyFeaturizer"
#   - name: "RegexFeaturizer"
#   - name: "SynonymMapper"
#   - name: "CRFEntityExtractor"
#   - name: "EntitySynonymMapper"
#   - name: "DucklingHTTPExtractor"
#   - name: "EntityExtractor"
#   - name: "CountVectorsFeaturizer"
#   - name: "EmbeddingIntentClassifier"

# # language: vi
# # pipeline:
# #   - name: WhitespaceTokenizer
# #   - name: LanguageModelFeaturizer
# #     model_name: "PhoBERT"
# #     model_weights: "vinai/phobert-base-v2"
# #   - name: DIETClassifier
# #     epochs: 200
# #   - name: EntitySynonymMapper
# # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # # If you'd like to customize it, uncomment and adjust the pipeline.
# # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   # - name: WhitespaceTokenizer
#   # - name: RegexFeaturizer
#   # - name: LexicalSyntacticFeaturizer
#   # - name: CountVectorsFeaturizer
#   # - name: CountVectorsFeaturizer
#   #   analyzer: char_wb
#   #   min_ngram: 1
#   #   max_ngram: 4
#   # - name: EmbeddingIntentClassifier
# #   - name: DIETClassifier
# #     epochs: 100
# #     constrain_similarities: true
# #   - name: EntitySynonymMapper
# #   - name: ResponseSelector
# #     epochs: 100
# #     constrain_similarities: true
# #   - name: FallbackClassifier
# #     threshold: 0.3
# #     ambiguity_threshold: 0.1


# # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # # If you'd like to customize it, uncomment and adjust the pipeline.
# # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
# #   - name: WhitespaceTokenizer
# #   - name: RegexFeaturizer
# #   - name: LexicalSyntacticFeaturizer
# #   - name: CountVectorsFeaturizer
# #   - name: CountVectorsFeaturizer
# #     analyzer: char_wb
# #     min_ngram: 1
# #     max_ngram: 4
# #   - name: DIETClassifier
# #     epochs: 100
# #     constrain_similarities: true
# #   - name: EntitySynonymMapper
# #   - name: ResponseSelector
# #     epochs: 100
# #     constrain_similarities: true
# #   - name: FallbackClassifier
# #     threshold: 0.3
# #     ambiguity_threshold: 0.1
# # policies: null
# # # No configuration for policies was provided. The following default policies were used to train your model.
# # # If you'd like to customize them, uncomment and adjust the policies.
# # # See https://rasa.com/docs/rasa/policies for more information.
# #   - name: MemoizationPolicy
# #   - name: RulePolicy
# #   - name: UnexpecTEDIntentPolicy
# #     max_history: 5
# #     epochs: 100
# #   - name: TEDPolicy
# #     max_history: 5
# #     epochs: 100
# #     constrain_similarities: true

# policies: null
# # # No configuration for policies was provided. The following default policies were used to train your model.
# # # If you'd like to customize them, uncomment and adjust the policies.
# # # See https://rasa.com/docs/rasa/policies for more information.
# #   - name: MemoizationPolicy
# #   - name: RulePolicy
# #   - name: UnexpecTEDIntentPolicy
# #     max_history: 5
# #     epochs: 100
# #   - name: TEDPolicy
# #     max_history: 5
# #     epochs: 100
# #     constrain_similarities: true
